apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: common-enode-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.storage.sharedStorageClass }}