apiVersion: v1
kind: ConfigMap
metadata:
  name: jsonrpc-config
data:
  start-jsonrpc.sh: |
    #!/bin/sh
    set -e

    BOOTNODE_ENODE=$(cat /common/enode.txt)
    echo "Bootnode enode: ${BOOTNODE_ENODE}"

    # Initialize geth with genesis file if not already initialized
    if [ ! -d /root/.ethereum/geth ]; then
      geth init /root/genesis.json
    fi

    # Start geth
    exec geth --datadir /root/.ethereum \
         --networkid {{ .Values.networkId }} \
         --bootnodes ${BOOTNODE_ENODE} \
         --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" \
         --http.api eth,net,web3,personal,miner